### PR TITLE
Awesome Books

### PR DESCRIPTION
**Pull request by AmaliaGM**
- We implemented basic UI with plain HTML:
- We created a collection that keeps a list of books 
- We created a function to add a new book to the collection, with title and author.
- We created a function to remove a book from the collection 
- We displayed all books saved in the collection in the top part of the page.
- We made sure that when a user clicks the "Add" button:
      A new book is added to the collection.
      The new book is displayed in the page.
- We made sure that when a user clicks the "Remove" button:
      The correct book is removed from the collection.
      The correct book dissapears from the page.
      Make sure that data is preserved in the browser's memory by using [localStorage]

### CODE REVIEW

**Review by Davidosky007 — COMMENTED** [review]
Hi @AmaliaGM @Tiago-Lelinski-Marin 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linter configurations setup [Kindly follow this link on how to properly setup linters](https://github.com/microverseinc/linters-config/tree/master/javascript). Also, customize your readme file to suit your project 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by ShadyShawkat — CHANGES_REQUESTED** [review]
## Hi @AmaliaGM, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

Image

## Required Changes ♻️
- [ ] Kindly make sure to edit your README.md file to suit your project more (please edit each section).


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tiagomarin** [comment]
Hey @ShadyShawkat how are you doing?

You wrote in the review: 
"Check the comments under the review."

But I can't find the comments.

**Comment by ShadyShawkat** [comment]
Hi @Tiago-Lelinski-Marin, thanks for pointing that out.

I apologize for leaving that part in, I should've removed it. I'll do that now.
The required change is the readme part.

**Review by julie-ify — CHANGES_REQUESTED** [review]
Hi @AmaliaGM and @Tiago-Lelinski-Marin, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] **[REQUIRED]** As requested by the previous reviewer, kindly edit your Readme and change the content to match your project because you just have the content from the template. Give your project a name. Add a good description of your project explaining the purpose of the project. Add the technologies and tools that were used in building the project. You can remove the live demo section if it's not deployed yet. In the Getting Started section of your Readme, include the instructions on how to clone and run your project locally. Add the correct social handles of the authors which are you and your partner. This is very important so that users can find instructions on how to successfully run your project and to make your repository more professional and informative.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tiagomarin** [comment]
Hey @julie-ify how are you?

We did everything but we did on the master branch = )

Thanks for being more specific about it, so we could find where/what was the problem!

**Review by SajjadAhmad14 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi team, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!

## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Ismailco — COMMENTED** [review]
Hi @AmaliaGM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already been approved, kindly check your PR before re-submitting again

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AmaliaGM** [comment]
> Hi @AmaliaGM,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has already been approved, kindly check your PR before re-submitting again
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit

**Pull request closed without merging**
